export enum E_Routes {
	home = "/",
	introduce = "/introduce",
	contact = "/contact",
	login = "/login",
	register = "/register",
	profile = "/profile?section=profile",
	admin = "/admin",
	docs = "/docs",
	about = "/about",
	privacy = "/privacy",
	terms = "/terms",
	dashboard = "/dashboard?section=overview",
	//DOCS
	getting_started = "/docs?section=getting_started",
	introduction = "/docs?section=introduction",
	logs = "/docs?section=logs",
	analytics = "/docs?section=analytics",
	npm_package = "https://www.npmjs.com/package/nna-sdk",
}
